version: '3.7'

services:
  django:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    command: ['bash', '-c', 'gunicorn config.wsgi:application -w 1 --bind 0.0.0.0:8000']
    volumes:
        - ./app/:/code/
    expose:
        - 8000
    env_file: env/settings.prod.env
    depends_on:
      - postgres

  postgres:
    image: postgres:11.4
    volumes:
      - db:/var/lib/postgresql/data
    env_file: env/postgres.prod.env

  nginx:
    build: ./nginx
    volumes:
      - static_volume:./app/deploy
    ports:
      - 1337:80
    depends_on:
      - django

volumes:
  db:
  static_volume:
